/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        //assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
